### ISSUE TITLE
Remove error bars?

### ISSUE THREAD

**Issue by bencamm001** [jeffersonfparil/violinplotter#15]
Is it possible to not plot error bars / mean?

**Comment by jeffersonfparil** [comment]
Dearest avid user a.k.a. ben,
I have fixed this issue. I added the option:
`PLOT_BAR=c(TRUE, FALSE, "stdev", "sterr", "ci")`
Please use the development version found here in github rather than the deployed CRAN version via:
`remotes::install_github("jeffersonfparil/violinplotter")`
Cheers!

**Comment by bencamm001** [comment]
can you also change it so the violin plots all start at values close to,
but no equal to zero. Julia does this by default and i think its much nicer
for all the violin plots to start at random points.

Cheers,

*Benjamin J. Camm | PhD Student*


School of BioSciences

Building 184 Room 317

The University of Melbourne, Victoria 3010 Australia

*T: *+61 4 1332 6163 *E: *bcamm@student.unimelb.edu.au
